"""empty message

Revision ID: 6546e510ecea
Revises: 77ca986210cc
Create Date: 2020-01-27 12:35:28.601407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6546e510ecea'
down_revision = '77ca986210cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_venue', 'Venue', ['name', 'address', 'city_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_venue', 'Venue', type_='unique')
    # ### end Alembic commands ###
