"""empty message

Revision ID: c09f9f6083f7
Revises: 6159da46470b
Create Date: 2020-01-22 10:59:29.779312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09f9f6083f7'
down_revision = '6159da46470b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'City', ['city_id'], ['id'])
    op.drop_column('Venue', 'city')
    op.drop_column('Venue', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'city_id')
    # ### end Alembic commands ###
