"""empty message

Revision ID: ec68b3e27615
Revises: cd4731ccd587
Create Date: 2020-01-27 12:52:17.156728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec68b3e27615'
down_revision = 'cd4731ccd587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_show', 'Show', ['artist_id', 'venue_id', 'start_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_show', 'Show', type_='unique')
    # ### end Alembic commands ###
